name: Build Nginx ModSecurity Packages


on:
  push:
    tags:
      - 'v*'


permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu20
            image: ubuntu:20.04
          - name: ubuntu22
            image: ubuntu:22.04
          - name: ubuntu24
            image: ubuntu:24.04
          - name: debian-bullseye
            image: debian:11
          - name: debian-bookworm
            image: debian:12

    name: ${{ matrix.name }}
    container:
      image: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v4
      - run: ./build.sh
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      # make artifacts available to the next job
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: out/*
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      # gather everything from all matrix jobs
      - uses: actions/download-artifact@v4
        with:
          path: collected

      - name: Create/Update GitHub Release & upload files
        uses: softprops/action-gh-release@v2
        with:
          files: |
            collected/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
